internal/impl/pure/bloblang_numbers.go

Add the `pow` method that returns the number raised to a specified exponent.
Ex.:
``` coffee
root.new_value = this.value.pow(2)
``` 
```coffee
root.new_value = this.value * 10.pow(-2)
```

Add `pow` method

---

internal/transaction/result_store.go
public/service/message.go
public/service/message_test.go
public/service/stream_builder.go
public/service/stream_schema.go

This is a suite of public APIs for:
- Creating a stream builder with a custom full config schema (allows us to customise default values)
- Receiving synchronous responses from messages created using the public APIs
These two features are required for creating a serverless handler using public APIs.

Add public APIs for custom stream builder schemas

---

internal/impl/pure/bloblang_numbers.go

Add the `sin`, `cos` and `tan` trigonometric methods:
- sin
- cos
- tan
and the Pi constant as a function to, among others, convert between radians and degrees.
```yml
root.new_value = (this.value * (pi() / 180)).sin()
```

Add `sin`, `cos`, `tan` trigonometric methods and `pi` function

---

internal/impl/io/input_websocket.go
internal/impl/io/output_websocket.go

Note: The `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables can be used as fallback when this field isn't set. Details here: <https://pkg.go.dev/golang.org/x/net/http/httpproxy#FromEnvironment>.

Add proxy_url field to the websocket components

---

internal/impl/io/bloblang_examples_test.go
internal/impl/pure/bloblang_examples_test.go
internal/impl/pure/bloblang_numbers.go

The example tests used to be performed in a single place, which was the same package responsible for generating the docs. However, that package now exists within the connect repository and so it makes sense to add the tests in here so that we can catch example issues earlier.

Add blobl example tests back in

---

internal/impl/pure/buffer_system_window.go
internal/impl/pure/processor_cached.go
public/service/message.go
public/service/message_batch_blobl.go
public/service/message_batch_blobl_test.go

Fixes https://github.com/redpanda-data/connect/issues/2668
The issue is that executing a batch-aware mapping requires an invocation for each message of a batch, but in order to interop into the internal mapping executor we need a batch in the internal form. The slow and naive version of this was allocating a new slice of internal messages for each invocation which is fine when there is only one execution per-batch.
However, in many cases these mappings are executed for each message and the performance is terrible. I've added a new API for ensuring the allocation only happens once per-batch which is a significant improvement. A PR on the connect repo for the relevant plugins will come afterwards.

Add new bloblang and interp executors for batches

---

CHANGELOG.md
internal/impl/pure/processor_retry.go
internal/impl/pure/processor_retry_test.go

Also add `retry_count` and `backoff_duration` metadata fields to this processor.
This is a rebase of https://github.com/redpanda-data/connect/pull/2590.

Add `max_retries` field to the `retry` processor

---

CHANGELOG.md
internal/bloblang/query/methods_strings.go
internal/bloblang/query/methods_test.go

This is related to https://github.com/redpanda-data/connect/issues/1253.

Add `escape_html` parameter to the `format_json` bloblang method

---

public/service/integration/stream_test_helpers.go

Reject messages which contain errors when running the integration test suite.
This comes in handy when one wants to attach some processors to the input(s) in integration tests for performing additional validations such as throwing an error if some expected metadata field isn't present or has the wrong value.

Tighten up stream integration tests

---

CHANGELOG.md
internal/bundle/package.go
internal/manager/mock/manager.go
internal/manager/type.go
internal/manager/type_test.go
public/service/resources.go
public/service/resources_test.go

This PR adds some public methods to the `*Resources` type that allows plugin authors to define shared values across plugin instanciations within a given resource ecosystem. These generic values are worth using above a global singleton as they respect the isolation of a given execution environment.

Generic plugin resources

---

public/service/processor.go

Also in `BatchProcessor.ProcessBatch()`.
According to Ash:
> You need to ensure that if you end up yielding N messages then you need to copy the original message N times rather than create N new instantiations. That's because we use the context from the original message to carry things like distributed tracing info and synchronous response mechanisms.

Fix docs typo in `Processor.Process()`

---

internal/cli/app.go
internal/cli/app_test.go
internal/cli/blobl/cli.go
internal/cli/common/logger.go
internal/cli/common/manager.go
internal/cli/common/opts.go
internal/cli/common/run_flags.go
internal/cli/common/service.go
internal/cli/create.go
internal/cli/create_test.go
internal/cli/echo.go
internal/cli/echo_test.go
internal/cli/lint.go
internal/cli/lint_test.go
internal/cli/list.go
internal/cli/run.go
internal/cli/streams.go
internal/cli/streams_test.go
internal/cli/studio/pull.go
internal/cli/studio/pull_runner.go
internal/cli/studio/sync_schema.go
internal/cli/template/lint.go
internal/cli/test/cli.go
internal/cli/test/command.go
public/service/service.go
public/service/servicetest/service.go

This PR does a bit of refactoring so that all CLI subcommands are easier to test. The first part is getting it rid of (almost all) calls to `os.Exit`, those are replaced directly with returned errors. The second is using customisable handles for stdout and stderr writing, as this allows us to properly test the output of various commands without ugly command injection.
I've also renamed the new `-c` flag for streams mode to `-o/--observability` to hopefully make it clearer what the intention of that config file is.

Improve CLI package testability

---

internal/config/schema.go

Having a static http field can cause data races when instanciating multiple stream builders, as they mutate the default value of that field.
Ref: https://github.com/warpstreamlabs/bento/issues/82

Always construct a new http docs field

---

internal/bundle/buffers.go
internal/bundle/caches.go
internal/bundle/environment.go
internal/bundle/environment_test.go
internal/bundle/inputs.go
internal/bundle/metrics.go
internal/bundle/outputs.go
internal/bundle/processors.go
internal/bundle/ratelimits.go
internal/bundle/scanners.go
internal/bundle/tracers.go
public/service/environment.go

This allows granular customisation of environment plugins for each component type. We'll need this for cloud builds as the more ambiguous call means we can't remove the `csv` input without losing the `csv` scanner.

Add individual with env methods

---

CHANGELOG.md
internal/impl/pure/output_switch.go
internal/impl/pure/output_switch_test.go
public/service/config.go

Fixes #58 which is caused by a regression introduced in v4.25.0 via commit bc1ebafa9.

Fix switch output metrics labels

---

CHANGELOG.md
internal/log/logrus.go
internal/log/logrus_test.go

Fixes https://github.com/redpanda-data/connect/issues/2754.
Also, I took a stab at refactoring the logrus tests.
Not sure if this is the best way to fix this issue...
PS: I wonder if `internal/log/wrap.go` also needs this fix.

Fix log messages which contain fmt strings

---

internal/message/data.go
internal/message/data_test.go

There's an optimisation where we're able to avoid performing deep copies when we know that the source message is already deep copied from an original. This fix enables this optimisation by fixing a redundant assignment bug.

Fix consecutive calls to AsStructuredMut

---

CHANGELOG.md
internal/httpclient/client.go
internal/httpclient/client_test.go
internal/httpclient/config.go

This allows users to disable the Go HTTP client's default behavior of transparently following 3XX status codes.
This came from a question in the community slack from a user that was trying to use the `Location` header of a response from the `http` processor.

feat: add follow_redirects field to http processor

---

CHANGELOG.md
internal/cli/common/opts.go
internal/cli/common/run_flags.go
internal/cli/common/service.go
public/service/service.go
public/service/service_test.go

In order to allow custom flags when running configs I've had to add an opt func in the public service package that passes `github.com/urfave/cli/v2` types through. This isn't ideal as it locks us into using this CLI library long term in order to preserve backwards compatibility. However, that was likely the case anyway.
The long term plan is to expose enough functionality in the public packages that library users can actually build their own CLIs and we can remove the cli package from benthos.

Add custom cli flags

---

CHANGELOG.md
internal/docs/format_yaml_path.go
internal/docs/format_yaml_path_test.go

This is going to useful on cloud, where we'd like to append and mutate SASL fields onto a users existing config.

Allow set flags to use negative array indexes

---

CHANGELOG.md
internal/message/data.go
internal/message/part.go
public/service/message.go

There might be optimizations to be done if the internal data is held as
bytes already (like reusing containers to save allocs when parsing lots of data).

perf: add checks for the internal data held by a message

---

CHANGELOG.md
internal/config/watcher_wasm.go

The file watcher doesn't apply to wasm builds, so make a no-op.
This fixes builds like:
```
GOOS=js GOARCH=wasm go build -o benthos.wasm ./cmd/benthos
```

Fix wasm build by stubbing noReread().

---

internal/cli/common/run_flags.go

Having the custom run flags skipped for hidden commands kind of made sense because it means we avoid adding new behaviour to old stuff. However, in connect this also prevents the default secrets flags from being applied when running with the deprecated `-c` flag, which breaks backwards compatibility.

Always add run flags even for hidden commands

---

public/service/output.go

Something I noticed when reading the code

use provided context for batched writer closing

---

go.mod
go.sum
internal/impl/pure/processor_benchmark.go
internal/impl/pure/processor_benchmark_test.go
internal/periodic/periodic.go
internal/periodic/periodic_test.go

This processor emits rough throughput metrics which is useful for ad-hoc speed measurements of different combinations of input and output plugins.

feat(benchmark): add benchmark processor

---

internal/stream/manager/api.go
internal/stream/manager/type.go
internal/stream/type.go

We use benthos/redpanda-connect as the pipeline service. Often the users don't really care about the at-least-once semantics too much and they just want the pipeline to be deleted/updated ASAP. 
This PR enhanced the stream API to support the `timeout` query parameter to achieve the goal

feat: allowed the caller to specify timeout for stream api

---

CHANGELOG.md
internal/cli/common/reader.go
internal/cli/common/run_flags.go
internal/cli/template/lint.go
internal/template/config.go
internal/template/template.go
internal/template/template_test.go
public/service/environment.go
public/service/service_test.go
public/service/stream_template_tester.go

Templates were being registered against a global environment, but custom CLIs are able to lock in a custom environment, in which case templates were skipped. I've fixed this as well as a few other locations where custom environments were being ignored.

Fix template usage with custom environments

---

CHANGELOG.md
internal/template/config.go
internal/template/template.go
internal/template/template_test.go

I could inject the test name as the label. Just thought it's nicer to have an explicit field.
Example usage:
`test.tmpl.yaml`:
```yaml
name: foobar
type: input
mapping: |
root.generate = {
"count": 1,
"mapping": "root = \"" + @label.or("") + "\""
}
tests:
- name: foobar test
label: quack
config: {}
expected:
generate:
count: 1
mapping: root = "quack"
```
`test.yaml`:
```yaml
input:
label: meow
foobar: {}
```
Test:
```shell
$ benthos template lint test.tmpl.yaml 
$ benthos run -t test.tmpl.yaml test.yaml
INFO Running main config from specified file       @service=benthos benthos_version=82851b0cfc4009c48115b56d4743848193def0d8 path=test.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
INFO Launching a Benthos instance, use CTRL+C to close  @service=benthos …
```

Add label metadata in template mapping

---

CHANGELOG.md
internal/impl/pure/processor_branch.go
internal/impl/pure/processor_branch_test.go
internal/impl/pure/processor_for_each.go
internal/impl/pure/processor_log_test.go
internal/log/testutil/mock_log.go

I added this test to get a discussion going on the logs emitted by the `branch` processor. As pointed out in https://github.com/redpanda-data/connect/issues/2333, they can be excessive in some cases.

Revise `branch` processor logging

---

CHANGELOG.md
internal/cli/app_test/app_test.go
internal/stream/docs.go
public/service/stream_builder_test/stream_builder_test.go

There's a bit of duplication with those tests... I can drop `internal/cli/app_test/app_test.go` since it uses the same underlying code as the StreamsBuilder API. WDYT?

Change default output to `reject` when `stdout` is not available

---

CHANGELOG.md
internal/template/config.go
internal/template/template_test.go

Example:
Template:
```yaml
name: foo
type: processor
status: experimental
fields:
- name: mapping
type: bloblang
mapping: |
root.mapping = this.mapping
```
Config:
```yaml
input:
generate:
count: 1
mapping: root = ""
processors:
- foo:
mapping: root.foo = "bar"
output:
stdout: {}
```
The main goal is to have the linter complain if `foo.mapping` doesn't contain valid Bloblang. It's also handy to be able to distinguish it from a plain string in the config schema.

Add `bloblang` scalar type to template fields

---

CHANGELOG.md
internal/impl/pure/output_broker.go
public/service/output.go
public/service/stream_builder.go
public/service/stream_builder_test/stream_builder_test.go

This allows users to configure the output brokering pattern for streams constructed programatically via the StreamBuilder APIs.

Add new `StreamBuilder.SetOutputBrokerPattern` API

---

CHANGELOG.md
internal/bloblang/query/errors.go
internal/bloblang/query/functions.go
internal/bloblang/query/functions_test.go
internal/component/errors.go
internal/component/processor/auto_observed.go
public/service/errors_test.go

- `error_source_name()`: Returns the name of the component which raised the error.
- `error_source_label()`: Returns the label of the component which raised the error.
- `error_source_path()`: Returns the config path of the conponent which raised the error.
One use case for these is to determine which processor generated an error within a `try` processor.
I thought about having only `error_source_label()` and returning the path when the label is not set, but it feels handy to be able to quickly print both the label and the path.
When using the same processor resource multiple times in a config, these functions won't help users figure out which config section caused the error, since the path is relative to
`processor_resources`. Templates don't have this issue because the path will be …

Add `error_source_*` bloblang functions

---

internal/impl/pure/processor_log.go

Fix the values for the level field of the log processor

---

public/service/codec/scanner.go
public/service/codec/scanner_test.go

This issue was uncovered because the `http_client` components would not try to reconnect if the internal codec couldn't be initialised. The fix addresses the issue at the scanner level.
`h.codecCtor.Create` will return a `*service.OwnedScanner`, but `h.codec` has type `codec.DeprecatedFallbackStream`, so if we get an error from `h.codecCtor.Create`, the `h.codec != nil` check in `Connect` will be true, so Benthos will think the input is connected. This can happen if the codec specification isn't compatible with the received data.

Fix http_client input connect bug

---

CHANGELOG.md
internal/cli/studio/pull_runner.go
internal/cli/studio/pull_runner_test.go

This allows Studio users with custom plugins to use a license as described here: https://github.com/redpanda-data/redpanda-connect-plugin-example/issues/28

Fix the `studio` `pull` CLI subcommand to trigger `OnManagerInitialised`

---

CHANGELOG.md
internal/docs/field.go
internal/docs/format_any.go
internal/docs/format_yaml.go
public/service/config_test.go

The `Contains()` method of `service.ParsedConfig` was returning `true` when using an optional `service.NewObjectField()` which wasn't set in the config.
This is required for https://github.com/redpanda-data/connect/pull/3165.
Code coverage for the test I added:
```shell
$ go test -cover -coverpkg=github.com/redpanda-data/benthos/v4/internal/docs -coverprofile cover.out -run ^TestOptionalConfigFields$ github.com/redpanda-data/benthos/v4/public/service
```
A few more statements are covered by the other tests.

Fix optional field handling in configs

---

CHANGELOG.md
internal/impl/io/input_socket_server.go
internal/impl/io/input_socket_server_test.go

Present `tls.ClientAuthType` values under `tls.client_auth` of `socket_server` input.

Add TLS client authentication for socket_server

---

CHANGELOG.md
internal/httpclient/client.go
internal/httpclient/client_test.go

Enable multi-value HTTP header support for the `http_client` input and output and for the `http` processor.
Fixes https://github.com/redpanda-data/connect/issues/1389.
PS: Technically, this is a small breaking change, but I think it's better to do it and maybe introduce a flag to toggle the old behaviour if it ends up preventing users from upgrading.

Support multi-value HTTP headers

---

CHANGELOG.md
internal/cli/app.go
public/service/resource_builder.go

Adds the ability to override the standard suite of cli subcommands. I've also added a way to inject logic into a resources init stage for the ResourceBuilder.

CLI command subcommands override

---

public/service/stream_builder_test/stream_builder_test.go

Thank you for reporting this @dcarbone!
I somehow forgot to close the stream when I wrote this test and then the #207 linting refactor made it flakey...

Fix broken test

---

CHANGELOG.md
internal/cli/blobl/cli.go
internal/cli/echo.go
internal/cli/lint.go

This fixes a regression introduced in v4.40.0 (commit https://github.com/redpanda-data/benthos/commit/48e6c4f412737e9b76bd2eab7af8630efb037d3d).
Also add the `--env-file` flag to the blobl command.
Fixes #223.
Fixes #195.
Fixes #149.

Fix env var loading

---

CHANGELOG.md
internal/bloblang/query/methods_numbers.go
internal/impl/pure/bloblang_numbers.go

Adds methods `bitwise_and()`, `bitwise_or()` and `bitwise_xor()` which work on integers and do what you expect.
The prefix is due to the name collision with `or`. Through the magic of the existing code structure, we have tests.

Add bitwise and/or/xor support for integers

---

CHANGELOG.md
internal/impl/io/input_socket.go
internal/impl/io/input_socket_test.go

Add optional `open_message_mapping` to `socket`, so we can send the result of a Bloblang mapping as an open message when making a connection.
This allows dynamic messages to be supported, such as time-dependent ones.
Contrived example:
```
input:
label: conn
socket:
network: tcp
address: 127.0.0.1:12345
open_message_mapping: root = (1 + 2).string() + "\n"
```
This sends `3\n` upstream.
The message being sent (typically for authentication) is not based on input, and is sent before any input is received. The Bloblang is called every time the socket connects or reconnects.

Add open_message_mapping to socket input

---

CHANGELOG.md
internal/impl/pure/bloblang_schema.go
public/schema/common.go
public/schema/common_test.go
public/schema/infer_from_any.go
public/schema/infer_from_any_test.go

The intention of this new package is to be a single place that multiple inputs, processors and outputs can use when sharing schema definitions. It will be possible to create adapters that translate schemas of various types to and from this common format. The goal of this package is to be a common subset of each schemas capabilities rather than a superset in order to maintain as wide a breadth of compatibility as possible.

Add common schemas package
